syntax = "proto3";

import "ASN1.proto";
import "Rfc5280.proto";
import "Rfc5755.proto";

package PlatformCertificateProto;

message PlatformAttributeCertificate {
  TcgCredentialType tCGCredentialType = 1 [(ASN1.asn1_type) = ASN1_SEQUENCE];
  DN issuer = 2 [(ASN1.asn1_type) = ASN1_SEQUENCE];
  AuthorityKeyIdentifier authorityKeyIdentifier = 3 [(ASN1.asn1_type) = ASN1_SEQUENCE];
  repeated AccessDescription authorityInfoAccess = 4 [(ASN1.asn1_type) = ASN1_SEQUENCE];
  TcgSpecificationVersion tCGCredentialSpecification = 5 [(ASN1.asn1_type) = ASN1_SEQUENCE];
  AttCertValidityPeriod attrCertValidityPeriod = 6 [(ASN1.asn1_type) = ASN1_SEQUENCE];
  AlgorithmIdentifier signature = 7 [(ASN1.asn1_type) = ASN1_SEQUENCE];
  AlgorithmIdentifier signatureAlgorithm = 8 [(ASN1.asn1_type) = ASN1_SEQUENCE];
  bytes signatureValue = 9 [(ASN1.asn1_type) = ASN1_BIT_STRING];
  repeated PolicyInformation certificatePolicies = 10 [(ASN1.asn1_type) = ASN1_SEQUENCE];
  repeated Trait previousPlatformCertificates = 11 [(ASN1.asn1_type) = ASN1_SEQUENCE];
  repeated DistributionPoint cRLDistributionPoints = 12 [(ASN1.asn1_type) = ASN1_SEQUENCE];
  IssuerSerial holder = 13 [(ASN1.asn1_type) = ASN1_SEQUENCE];
  repeated Trait cryptographicAnchors = 14 [(ASN1.asn1_type) = ASN1_SEQUENCE];
  repeated Trait platformIdentifier = 15 [(ASN1.asn1_type) = ASN1_SEQUENCE];
  TcgPlatformSpecification tCGPlatformSpecification = 16 [(ASN1.asn1_type) = ASN1_SEQUENCE];
  repeated Trait tBBSecurityAssertions = 17 [(ASN1.asn1_type) = ASN1_SEQUENCE];
  PlatformConfiguration platformConfiguration = 18 [(ASN1.asn1_type) = ASN1_SEQUENCE];
  repeated Trait platformConfigUri = 19 [(ASN1.asn1_type) = ASN1_SEQUENCE];
  repeated Trait platformOwnership = 20 [(ASN1.asn1_type) = ASN1_SEQUENCE];
  repeated Trait manufacturingAssertions = 21 [(ASN1.asn1_type) = ASN1_SEQUENCE];
}

message PlatformKeyCertificate {
  TcgCredentialType tCGCredentialType = 1 [(ASN1.asn1_type) = ASN1_SEQUENCE];
  DN issuer = 2 [(ASN1.asn1_type) = ASN1_SEQUENCE];
  AuthorityKeyIdentifier authorityKeyIdentifier = 3 [(ASN1.asn1_type) = ASN1_SEQUENCE];
  repeated AccessDescription authorityInfoAccess = 4 [(ASN1.asn1_type) = ASN1_SEQUENCE];
  TcgSpecificationVersion tCGCredentialSpecification = 5 [(ASN1.asn1_type) = ASN1_SEQUENCE];
  Validity validity = 6 [(ASN1.asn1_type) = ASN1_SEQUENCE];
  AlgorithmIdentifier signature = 7 [(ASN1.asn1_type) = ASN1_SEQUENCE];
  AlgorithmIdentifier signatureAlgorithm = 8 [(ASN1.asn1_type) = ASN1_SEQUENCE];
  bytes signatureValue = 9 [(ASN1.asn1_type) = ASN1_BIT_STRING];
  repeated PolicyInformation certificatePolicies = 10 [(ASN1.asn1_type) = ASN1_SEQUENCE];
  repeated Trait previousPlatformCertificates = 11 [(ASN1.asn1_type) = ASN1_SEQUENCE];
  repeated DistributionPoint cRLDistributionPoints = 12 [(ASN1.asn1_type) = ASN1_SEQUENCE];
  SubjectPublicKeyInfo subjectPublicKeyInfo = 13 [(ASN1.asn1_type) = ASN1_SEQUENCE];
  DN subject = 14 [(ASN1.asn1_type) = ASN1_SEQUENCE];
  SubjectKeyIdentifier subjectKeyIdentifier = 15 [(ASN1.asn1_type) = ASN1_SEQUENCE];
  repeated Trait cryptographicAnchors = 16 [(ASN1.asn1_type) = ASN1_SEQUENCE];
  repeated Trait platformIdentifier = 17 [(ASN1.asn1_type) = ASN1_SEQUENCE];
  TcgPlatformSpecification tCGPlatformSpecification = 18 [(ASN1.asn1_type) = ASN1_SEQUENCE];
  repeated Trait tBBSecurityAssertions = 19 [(ASN1.asn1_type) = ASN1_SEQUENCE];
  PlatformConfiguration platformConfiguration = 20 [(ASN1.asn1_type) = ASN1_SEQUENCE];
  repeated Trait platformConfigUri = 21 [(ASN1.asn1_type) = ASN1_SEQUENCE];
  repeated Trait platformOwnership = 22 [(ASN1.asn1_type) = ASN1_SEQUENCE];
  repeated Trait manufacturingAssertions = 23 [(ASN1.asn1_type) = ASN1_SEQUENCE];
}

message TcgCredentialType {
  // certificateType values: tcg-kp-PlatformAttributeCertificate, -PlatformKeyCertificate,
  //                               -AdditionalPlatformAttributeCertificate, -AdditionalPlatformKeyCertificate,
  //                               -DeltaPlatformAttributeCertificate, -DeltaPlatformKeyCertificate
  string certificateType = 1 [(ASN1.asn1_type) = ASN1_OBJECT_IDENTIFIER];
}

message TcgSpecificationVersion {
  sint64 majorVersion = 1 [(ASN1.asn1_type) = ASN1_INTEGER];
  sint64 minorVersion = 2 [(ASN1.asn1_type) = ASN1_INTEGER];
  sint64 revision = 3 [(ASN1.asn1_type) = ASN1_INTEGER];
}

message TcgPlatformSpecification {
  TcgSpecificationVersion version = 1 [(ASN1.asn1_type) = ASN1_SEQUENCE];
  bytes platformClass = 2 [(ASN1.asn1_type) = ASN1_OCTET_STRING];
}

message TraitList {
  repeated Trait traits = 1 [(ASN1.asn1_type) = ASN1_SEQUENCE];
}

message Trait {
  string traitId = 1 [(ASN1.asn1_type) = ASN1_OBJECT_IDENTIFIER];
  string traitCategory = 2 [(ASN1.asn1_type) = ASN1_OBJECT_IDENTIFIER];
  string traitRegistry = 3 [(ASN1.asn1_type) = ASN1_OBJECT_IDENTIFIER];
  string description = 4 [(ASN1.asn1_type) = ASN1_UTF8STRING];
  string descriptionURI = 5 [(ASN1.asn1_type) = ASN1_IA5STRING];
  oneof traitValue {
    // Generic buckets to pass data. Trait ID, category, and registry will determine how to interpret any traitValue.
    bytes asn1 = 6;
    sint64 intValue = 7;
    string stringValue = 8;
    // traitId: tcg-tr-ID-Boolean
    bool booleanValue = 9 [(ASN1.asn1_type) = ASN1_BOOLEAN];
    // traitId: tcg-tr-ID-certificateIdentifier
    // traitCategory values: tcg-tr-cat-EKCertificate, -IAKCertificate, -IDevIDCertificate, -DICECertificate,
    //                                 -SPDMCertificate, -PlatformCertificate, -DeltaPlatformCertificate,
    //                                 -RebasePlatformCertificate, -genericCertificate
    CertificateIdentifier certificateIdentifier = 10 [(ASN1.asn1_type) = ASN1_SEQUENCE];
    // traitId: tcg-tr-ID-CommonCriteria
    // traitCategory: tcg-tr-cat-CommonCriteria
    CommonCriteriaEvaluation commonCriteria = 11 [(ASN1.asn1_type) = ASN1_SEQUENCE];
    // traitId: tcg-tr-ID-componentClass
    // traitCategory: tcg-tr-cat-componentClass
    bytes componentClassValue = 12 [(ASN1.asn1_type) = ASN1_OCTET_STRING];
    // traitId: tcg-tr-ID-componentIdentifierV11
    // traitCategory: tcg-tr-cat-componentIdentifierV11
    ComponentIdentifierV11 componentIdentifierV11 = 13 [(ASN1.asn1_type) = ASN1_SEQUENCE];
    // traitId: tcg-tr-ID-FIPSLevel
    // traitCategory: tcg-tr-cat-FIPSLevel
    FipsLevel fipsLevel = 14 [(ASN1.asn1_type) = ASN1_SEQUENCE];
    // traitId: tcg-tr-ID-ISO9000
    // traitCategory: tcg-tr-cat-ISO9000
    Iso9000Certification iso9000 = 15 [(ASN1.asn1_type) = ASN1_SEQUENCE];
    // traitId: tcg-tr-ID-networkMAC
    // traitCategory: tcg-tr-cat-networkMAC
    ComponentAddress networkMAC = 16 [(ASN1.asn1_type) = ASN1_SEQUENCE];
    // traitId: tcg-tr-ID-OID
    // traitCategory: tcg-tr-cat-OID
    string oid = 17 [(ASN1.asn1_type) = ASN1_OBJECT_IDENTIFIER];
    // traitId: tcg-tr-ID-PEN
    // traitCategory: tcg-tr-cat-PEN
    string pen = 18 [(ASN1.asn1_type) = ASN1_OBJECT_IDENTIFIER];
    // traitId: tcg-tr-ID-platformFirmwareCapabilities
    // traitCategory: tcg-tr-cat-platformFirmwareCapabilities
    PlatformFirmwareCapabilitiesList platformFirmwareCapabilities = 19 [(ASN1.asn1_type) = ASN1_BIT_STRING];
    // traitId: tcg-tr-ID-platformFirmwareSignatureVerification
    // traitCategory: tcg-tr-cat-platformFirmwareSignatureVerification
    PlatformFirmwareSignatureVerificationList platformFirmwareSignatureVerification = 20 [(ASN1.asn1_type) = ASN1_BIT_STRING];
    // traitId: tcg-tr-ID-platformFirmwareUpdateCompliance
    // traitCategory: tcg-tr-cat-platformFirmwareUpdateCompliance
    PlatformFirmwareUpdateComplianceList platformFirmwareUpdateCompliance = 21 [(ASN1.asn1_type) = ASN1_BIT_STRING];
    // traitId: tcg-tr-ID-platformHardwareCapabilities
    // traitCategory: tcg-tr-cat-platformHardwareCapabilities
    PlatformHardwareCapabilitiesList platformHardwareCapabilities = 22 [(ASN1.asn1_type) = ASN1_BIT_STRING];
    // traitId: tcg-tr-ID-RTM
    // traitCategory: tcg-tr-cat-RTM
    RTMTypesList rTMTypes = 23 [(ASN1.asn1_type) = ASN1_BIT_STRING];
    // traitId: tcg-tr-ID-status
    AttributeStatus status = 24 [(ASN1.asn1_type) = ASN1_ENUMERATED];
    // traitId: tcg-tr-ID-URI
    URIReference uri = 25 [(ASN1.asn1_type) = ASN1_SEQUENCE];
    // traitId: tcg-tr-ID-UTF8String
    string utf8 = 26 [(ASN1.asn1_type) = ASN1_UTF8STRING];
    // traitId: tcg-tr-ID-IA5String
    string ia5 = 27 [(ASN1.asn1_type) = ASN1_IA5STRING];
    // traitId: tcg-tr-ID-PEMCertString
    // traitCategory: tcg-tr-cat-PEMCertificate
    string pem = 28 [(ASN1.asn1_type) = ASN1_UTF8STRING];
    // traitId: tcg-tr-ID-PublicKey
    // traitCategory: tcg-tr-cat-PublicKey
    SubjectPublicKeyInfo publicKey = 29 [(ASN1.asn1_type) = ASN1_SEQUENCE];
    // traitId: tcg-tr-ID-entGeoLocation
    // traitCategory: tcg-tr-cat-entGeoLocation
    EntityGeoLocation entGeoLocation = 30 [(ASN1.asn1_type) = ASN1_SEQUENCE];
    // traitId: tcg-tr-ID-countryOfOrigin
    // traitCategory: tcg-tr-cat-countryOfOrigin
    OriginComposition countryOfOrigin = 31 [(ASN1.asn1_type) = ASN1_SEQUENCE];
  }
}

message PlatformFirmwareCapabilitiesList {
  repeated PlatformFirmwareCapabilities values = 6 [(ASN1.asn1_type) = ASN1_BIT_STRING];
}

message PlatformFirmwareSignatureVerificationList {
  repeated PlatformFirmwareSignatureVerification values = 6 [(ASN1.asn1_type) = ASN1_BIT_STRING];
}

message PlatformFirmwareUpdateComplianceList {
  repeated PlatformFirmwareUpdateCompliance values = 6 [(ASN1.asn1_type) = ASN1_BIT_STRING];
}

message PlatformHardwareCapabilitiesList {
  repeated PlatformHardwareCapabilities values = 6 [(ASN1.asn1_type) = ASN1_BIT_STRING];
}

message RTMTypesList {
  repeated RTMTypes values = 6 [(ASN1.asn1_type) = ASN1_BIT_STRING];
}

message CertificateIdentifier {
  HashedCertificateIdentifier hashedCertIdentifier = 1 [(ASN1.asn1_type) = ASN1_SEQUENCE];
  IssuerSerial genericCertIdentifier = 2 [(ASN1.asn1_type) = ASN1_SEQUENCE];
}

message HashedCertificateIdentifier {
  AlgorithmIdentifier hashAlgorithm = 1 [(ASN1.asn1_type) = ASN1_SEQUENCE];
  bytes hashOverSignatureValue = 2 [(ASN1.asn1_type) = ASN1_OCTET_STRING];
}

message CommonCriteriaEvaluation {
  CommonCriteriaMeasures commonCriteriaMeasures = 1 [(ASN1.asn1_type) = ASN1_SEQUENCE];
  string cCCertificateNumber = 2 [(ASN1.asn1_type) = ASN1_UTF8STRING];
  string cCCertificateAuthority = 3 [(ASN1.asn1_type) = ASN1_UTF8STRING];
  string evaluationScheme = 4 [(ASN1.asn1_type) = ASN1_UTF8STRING];
  string cCCertificateIssuanceDate = 5 [(ASN1.asn1_type) = ASN1_GENERALIZEDTIME];
  string cCCertificateExpiryDate = 6 [(ASN1.asn1_type) = ASN1_GENERALIZEDTIME];
}

message CommonCriteriaMeasures {
  string version = 1 [(ASN1.asn1_type) = ASN1_IA5STRING];
  EvaluationAssuranceLevel assuranceLevel = 2 [(ASN1.asn1_type) = ASN1_ENUMERATED];
  EvaluationStatus evaluationStatus = 3 [(ASN1.asn1_type) = ASN1_ENUMERATED];
  bool plus = 4 [(ASN1.asn1_type) = ASN1_BOOLEAN];
  StrengthOfFunction strengthOfFunction = 5 [(ASN1.asn1_type) = ASN1_ENUMERATED];
  string profileOid = 6 [(ASN1.asn1_type) = ASN1_OBJECT_IDENTIFIER];
  URIReference profileUri = 7 [(ASN1.asn1_type) = ASN1_SEQUENCE];
  string targetOid = 8 [(ASN1.asn1_type) = ASN1_OBJECT_IDENTIFIER];
  URIReference targetUri = 9 [(ASN1.asn1_type) = ASN1_SEQUENCE];
}

enum EvaluationAssuranceLevel {
  EVALUATIONASSURANCELEVEL_LEVEL0 = 0;
  EVALUATIONASSURANCELEVEL_LEVEL1 = 1;
  EVALUATIONASSURANCELEVEL_LEVEL2 = 2;
  EVALUATIONASSURANCELEVEL_LEVEL3 = 3;
  EVALUATIONASSURANCELEVEL_LEVEL4 = 4;
  EVALUATIONASSURANCELEVEL_LEVEL5 = 5;
  EVALUATIONASSURANCELEVEL_LEVEL6 = 6;
  EVALUATIONASSURANCELEVEL_LEVEL7 = 7;
}

enum EvaluationStatus {
  EVALUATIONSTATUS_DESIGNEDTOMEET = 0;
  EVALUATIONSTATUS_EVALUATIONINPROGRESS = 1;
  EVALUATIONSTATUS_EVALUATIONCOMPLETED = 2;
}

enum StrengthOfFunction {
  STRENGTHOFFUNCTION_BASIC = 0;
  STRENGTHOFFUNCTION_MEDIUM = 1;
  STRENGTHOFFUNCTION_HIGH = 2;
}

message URIReference {
  string uniformResourceIdentifier = 1 [(ASN1.asn1_type) = ASN1_IA5STRING];
  AlgorithmIdentifier hashAlgorithm = 2 [(ASN1.asn1_type) = ASN1_SEQUENCE];
  bytes hashValue = 3 [(ASN1.asn1_type) = ASN1_BIT_STRING];
}

message FipsLevel {
  string version = 1 [(ASN1.asn1_type) = ASN1_IA5STRING];
  SecurityLevel level = 2 [(ASN1.asn1_type) = ASN1_ENUMERATED];
  bool plus = 3 [(ASN1.asn1_type) = ASN1_BOOLEAN];
}

enum SecurityLevel {
  SECURITYLEVEL_LEVEL0 = 0;
  SECURITYLEVEL_LEVEL1 = 1;
  SECURITYLEVEL_LEVEL2 = 2;
  SECURITYLEVEL_LEVEL3 = 3;
  SECURITYLEVEL_LEVEL4 = 4;
}

message Iso9000Certification {
  bool iso9000Certified = 1 [(ASN1.asn1_type) = ASN1_BOOLEAN];
  string iso9000Uri = 2 [(ASN1.asn1_type) = ASN1_IA5STRING];
}

enum PlatformFirmwareCapabilities {
  PLATFORMFIRMWARECAPABILITIES_FWSETUPAUTHLOCAL = 0;
  PLATFORMFIRMWARECAPABILITIES_FWSETUPAUTHREMOTE = 1;
  PLATFORMFIRMWARECAPABILITIES_SMMPROTECTION = 2;
  PLATFORMFIRMWARECAPABILITIES_FWKERNELDMAPROTECTION = 3;
}

enum PlatformFirmwareSignatureVerification {
  PLATFORMFIRMWARESIGNATUREVERIFICATION_HARDWARESRTM = 0;
  PLATFORMFIRMWARESIGNATUREVERIFICATION_SECUREBOOT = 1;
}

enum PlatformFirmwareUpdateCompliance {
  PLATFORMFIRMWAREUPDATECOMPLIANCE_SP800_147 = 0;
  PLATFORMFIRMWAREUPDATECOMPLIANCE_SP800_147B = 1;
  PLATFORMFIRMWAREUPDATECOMPLIANCE_SP800_193 = 2;
}

enum PlatformHardwareCapabilities {
  PLATFORMHARDWARECAPABILITIES_IOMMUSUPPORT = 0;
  PLATFORMHARDWARECAPABILITIES_TRUSTEDEXECUTIONENVIRONMENT = 1;
  PLATFORMHARDWARECAPABILITIES_PHYSICALTAMPERPROTECTION = 2;
  PLATFORMHARDWARECAPABILITIES_PHYSICALTAMPERDETECTION = 3;
  PLATFORMHARDWARECAPABILITIES_FIRMWAREFLASHWP = 4;
  PLATFORMHARDWARECAPABILITIES_EXTERNALDMASUPPORT = 5;
}

enum RTMTypes {
  RTMTYPES_STATIC = 0;
  RTMTYPES_DYNAMIC = 1;
  RTMTYPES_NONHOST = 2;
  RTMTYPES_VIRTUAL = 3;
  RTMTYPES_HARDWARESTATIC = 4;
  RTMTYPES_BMC = 5;
}

message PlatformConfiguration {
  repeated TraitList platformComponents = 4 [(ASN1.asn1_type) = ASN1_SEQUENCE];
  repeated Property platformProperties = 2 [(ASN1.asn1_type) = ASN1_SEQUENCE];
}

message ComponentIdentifierV11 {
  ComponentClass componentClass = 1 [(ASN1.asn1_type) = ASN1_SEQUENCE];
  string componentManufacturer = 2 [(ASN1.asn1_type) = ASN1_UTF8STRING];
  string componentModel = 3 [(ASN1.asn1_type) = ASN1_UTF8STRING];
  string componentSerial = 4 [(ASN1.asn1_type) = ASN1_UTF8STRING];
  string componentRevision = 5 [(ASN1.asn1_type) = ASN1_UTF8STRING];
  string componentManufacturerId = 6 [(ASN1.asn1_type) = ASN1_OBJECT_IDENTIFIER];
  bool fieldReplaceable = 7 [(ASN1.asn1_type) = ASN1_BOOLEAN];
  repeated ComponentAddress componentAddresses = 8 [(ASN1.asn1_type) = ASN1_SEQUENCE];
  CertificateIdentifier componentPlatformCert = 9 [(ASN1.asn1_type) = ASN1_SEQUENCE];
  URIReference componentPlatformCertUri = 10 [(ASN1.asn1_type) = ASN1_SEQUENCE];
  AttributeStatus status = 11 [(ASN1.asn1_type) = ASN1_ENUMERATED];
}

message ComponentClass {
  string componentClassRegistry = 1 [(ASN1.asn1_type) = ASN1_OBJECT_IDENTIFIER];
  bytes componentClassValue = 2 [(ASN1.asn1_type) = ASN1_OCTET_STRING];
}

message ComponentAddress {
  string addressType = 1 [(ASN1.asn1_type) = ASN1_OBJECT_IDENTIFIER];                        // tcg-address-ethernetmac, -wlanmac, -bluetoothmac
  string addressValue = 2 [(ASN1.asn1_type) = ASN1_UTF8STRING];
}

message Property {
  string propertyName = 1 [(ASN1.asn1_type) = ASN1_UTF8STRING];
  string propertyValue = 2 [(ASN1.asn1_type) = ASN1_UTF8STRING];
  AttributeStatus status = 3 [(ASN1.asn1_type) = ASN1_ENUMERATED];
}

enum AttributeStatus {
  ATTRIBUTESTATUS_ADDED = 0;
  ATTRIBUTESTATUS_MODIFIED = 1;
  ATTRIBUTESTATUS_REMOVED = 2;
}

message EntityGeoLocation {
  string countryCode = 1 [(ASN1.asn1_type) = ASN1_PRINTABLESTRING];
  string stateOrProvince = 2 [(ASN1.asn1_type) = ASN1_PRINTABLESTRING];
  string localityName = 3 [(ASN1.asn1_type) = ASN1_UTF8STRING];
  string streetAddress = 4 [(ASN1.asn1_type) = ASN1_UTF8STRING];
  string locationCoords = 5 [(ASN1.asn1_type) = ASN1_PRINTABLESTRING];
  string postalCode = 6 [(ASN1.asn1_type) = ASN1_UTF8STRING];
}

message OriginComposition {
  EntityGeoLocation location = 1 [(ASN1.asn1_type) = ASN1_SEQUENCE];
  bool hasComponents = 2 [(ASN1.asn1_type) = ASN1_BOOLEAN];
}

