syntax = "proto3";

import "ASN1.proto";

message Certificate {
  TBSCertificate tbsCertificate = 1 [(ASN1.asn1_type) = ASN1_SEQUENCE];
  AlgorithmIdentifier signatureAlgorithm = 2 [(ASN1.asn1_type) = ASN1_SEQUENCE];
  bytes signatureValue = 3 [(ASN1.asn1_type) = ASN1_BIT_STRING];
}

message TBSCertificate {
  Rfc5280Version version = 1 [(ASN1.asn1_type) = ASN1_INTEGER];
  sint64 serialNumber = 2 [(ASN1.asn1_type) = ASN1_INTEGER];
  AlgorithmIdentifier signature = 3 [(ASN1.asn1_type) = ASN1_SEQUENCE];
  Name issuer = 4 [(ASN1.asn1_type) = ASN1_SEQUENCE];
  Validity validity = 5 [(ASN1.asn1_type) = ASN1_SEQUENCE];
  Name subject = 6 [(ASN1.asn1_type) = ASN1_SEQUENCE];
  SubjectPublicKeyInfo subjectPublicKeyInfo = 7 [(ASN1.asn1_type) = ASN1_SEQUENCE];
  bytes issuerUniqueID = 8 [(ASN1.asn1_type) = ASN1_BIT_STRING]; // UniqueIdentifier
  bytes subjectUniqueID = 9 [(ASN1.asn1_type) = ASN1_BIT_STRING]; // UniqueIdentifier
  repeated Extension extensions = 10 [(ASN1.asn1_type) = ASN1_SEQUENCE];
}

enum Rfc5280Version {
  RFC5280_V1 = 0;
  RFC5280_V2 = 1;
  RFC5280_V3 = 2;
}

message AlgorithmIdentifier {
  string algorithm = 1 [(ASN1.asn1_type) = ASN1_OBJECT_IDENTIFIER];
  AlgorithmIdentifierParameters parameters = 2;
}

message AlgorithmIdentifierParameters {
  oneof AlgorithmIdentifierParameters_oneof {
    ASN1.Null null = 2 [(ASN1.asn1_type) = ASN1_NULL];
    bytes bytes = 3;                                       // base64 encode the binary value
    string string = 4;
  }
}

message Name {
  oneof Name_oneof { // CHOICE
    RDNSequence rdnSequence = 1 [(ASN1.asn1_type) = ASN1_SEQUENCE];
  }
}

message RDNSequence {
  repeated RelativeDistinguishedName rdn = 1 [(ASN1.asn1_type) = ASN1_SET];
}

message RelativeDistinguishedName {
  AttributeTypeAndValue AttributeTypeAndValue = 1 [(ASN1.asn1_type) = ASN1_SEQUENCE];
}

message Attribute {
  string type = 1 [(ASN1.asn1_type) = ASN1_OBJECT_IDENTIFIER];
  repeated AttributeValue values = 2;
}

message AttributeTypeAndValue {
  string type = 1 [(ASN1.asn1_type) = ASN1_OBJECT_IDENTIFIER];
  AttributeValue value = 2; // ANY
}

message AttributeValue {
  oneof AttributeValue_oneof {
    string StringValue = 2 [(ASN1.asn1_type) = ASN1_UTF8STRING];
    bytes ByteValue = 3 [(ASN1.asn1_type) = ASN1_OCTET_STRING];
    sint64 IntValue = 4 [(ASN1.asn1_type) = ASN1_INTEGER];
    string OidValue = 5 [(ASN1.asn1_type) = ASN1_OBJECT_IDENTIFIER];
  }
}

message DN {
  oneof DN_oneof {
    Name name = 1 [(ASN1.asn1_type) = ASN1_SEQUENCE];
    string rdnShorthand = 2;
  }
}

message AttributeTypeAndDirectoryStringValue {
  string type = 1 [(ASN1.asn1_type) = ASN1_OBJECT_IDENTIFIER];
  DirectoryString value = 2;
}

message DirectoryString {
  oneof DirectoryString_oneof {  // CHOICE
    string teletexString = 1 [(ASN1.asn1_type) = ASN1_TELETEXSTRING];
    string printableString = 2 [(ASN1.asn1_type) = ASN1_PRINTABLESTRING];
    string universalString = 3 [(ASN1.asn1_type) = ASN1_UNIVERSALSTRING];
    string utf8String = 4 [(ASN1.asn1_type) = ASN1_UTF8STRING];
    string bmpString = 5 [(ASN1.asn1_type) = ASN1_BMPSSTRING];
  }
}

message Validity {
  ASN1.Time notBefore = 1;
  ASN1.Time notAfter = 2;
}

message SubjectPublicKeyInfo {
  AlgorithmIdentifier algorithm = 1 [(ASN1.asn1_type) = ASN1_SEQUENCE];
  bytes subjectPublicKey = 2 [(ASN1.asn1_type) = ASN1_BIT_STRING];
}

message UniqueIdentifier {
  bytes uid = 1 [(ASN1.asn1_type) = ASN1_BIT_STRING];
}

// Extension = repeated Extension
message Extension {
  string extnID = 1 [(ASN1.asn1_type) = ASN1_OBJECT_IDENTIFIER];
  bool critical = 2 [(ASN1.asn1_type) = ASN1_BOOLEAN];
  bytes extnValue = 3 [(ASN1.asn1_type) = ASN1_OCTET_STRING];
}

// GeneralNames = repeated GeneralName
message GeneralName {
  oneof GeneralName_oneof { // CHOICE
    OtherName otherName = 1 [(ASN1.asn1_type) = ASN1_SEQUENCE];
    string rfc822Name = 2 [(ASN1.asn1_type) = ASN1_IA5STRING];
    string dNSName = 3 [(ASN1.asn1_type) = ASN1_IA5STRING];
    bytes x400Address = 4 [(ASN1.asn1_type) = ASN1_OCTET_STRING];   // Chose not to include ORAddress at this time.
    Name directoryName = 5 [(ASN1.asn1_type) = ASN1_SEQUENCE];
    bytes ediPartyName = 6 [(ASN1.asn1_type) = ASN1_OCTET_STRING];  // Chose not to include EDIPartyName at this time.
    string uniformResourceIdentifier = 7 [(ASN1.asn1_type) = ASN1_IA5STRING];
    bytes iPAddress = 8 [(ASN1.asn1_type) = ASN1_OCTET_STRING];
    string registeredID = 9 [(ASN1.asn1_type) = ASN1_OBJECT_IDENTIFIER];
  }
}

message OtherName {
  string type_id = 1 [(ASN1.asn1_type) = ASN1_OBJECT_IDENTIFIER];
  bytes value = 2;
}

message ORAddress {
  BuiltInStandardAttributes builtInStandardAttributes = 1;
  BuiltInDomainDefinedAttributes builtInDomainDefinedAttributes = 2;
  ExtensionAttributes extensionAttributes = 3;
}

message EDIPartyName {
  DirectoryString nameAssigner = 1; // CHOICE
  DirectoryString partyName = 2; // CHOICE
}

message BuiltInStandardAttributes {
  CountryName countryName = 1 [(ASN1.asn1_type) = ASN1_SEQUENCE];
  AdministrationDomainName administrationDomainName = 2 [(ASN1.asn1_type) = ASN1_SEQUENCE];
  NetworkAddress networkAddress = 3 [(ASN1.asn1_type) = ASN1_SEQUENCE];
  string terminalIdentifier = 4 [(ASN1.asn1_type) = ASN1_PRINTABLESTRING];  // TerminalIdentifier
  PrivateDomainName privateDomainName = 5 [(ASN1.asn1_type) = ASN1_SEQUENCE];
  OrganizationName organizationName = 6 [(ASN1.asn1_type) = ASN1_SEQUENCE];
  NumericUserIdentifier numericUserIdentifier = 7 [(ASN1.asn1_type) = ASN1_SEQUENCE];
  PersonalName personalName = 8 [(ASN1.asn1_type) = ASN1_SEQUENCE];
  OrganizationalUnitNames organizationalUnitNames = 9 [(ASN1.asn1_type) = ASN1_SEQUENCE];
}

message CountryName {
  string x121DccCode = 1 [(ASN1.asn1_type) = ASN1_NUMERICSTRING];          // NumericString
  string iso3166Alpha2Code = 2 [(ASN1.asn1_type) = ASN1_PRINTABLESTRING];  // PrintableString
}

message AdministrationDomainName {
  string numeric = 1 [(ASN1.asn1_type) = ASN1_NUMERICSTRING];              // NumericString
  string printable = 2 [(ASN1.asn1_type) = ASN1_PRINTABLESTRING];          // PrintableString
}

message NetworkAddress {
  string x121Address = 1 [(ASN1.asn1_type) = ASN1_NUMERICSTRING];          // NumericString
}

message PrivateDomainName {
  oneof PrivateDomainName_oneof {
    string numeric = 1 [(ASN1.asn1_type) = ASN1_NUMERICSTRING];
    string printable = 2 [(ASN1.asn1_type) = ASN1_PRINTABLESTRING];
  }
}

message OrganizationName {
  string value = 1 [(ASN1.asn1_type) = ASN1_PRINTABLESTRING];
}

message NumericUserIdentifier {
  string value = 1 [(ASN1.asn1_type) = ASN1_NUMERICSTRING];
}

message PersonalName {
  string surname = 1 [(ASN1.asn1_type) = ASN1_PRINTABLESTRING];
  string given_name = 2 [(ASN1.asn1_type) = ASN1_PRINTABLESTRING];
  string initials = 3 [(ASN1.asn1_type) = ASN1_PRINTABLESTRING];
  string generation_qualifier = 4 [(ASN1.asn1_type) = ASN1_PRINTABLESTRING];
}

message OrganizationalUnitNames {
  repeated OrganizationalUnitName sequence = 1 [(ASN1.asn1_type) = ASN1_SEQUENCE];
}

message OrganizationalUnitName {
  string value = 1 [(ASN1.asn1_type) = ASN1_PRINTABLESTRING];
}

message BuiltInDomainDefinedAttributes {
  repeated BuiltInDomainDefinedAttribute sequence = 1 [(ASN1.asn1_type) = ASN1_SEQUENCE];
}

message BuiltInDomainDefinedAttribute {
  string type = 1 [(ASN1.asn1_type) = ASN1_PRINTABLESTRING];
  string value = 2 [(ASN1.asn1_type) = ASN1_PRINTABLESTRING];
}

message ExtensionAttributes {
  repeated ExtensionAttribute sequence = 1 [(ASN1.asn1_type) = ASN1_SEQUENCE];
}

message ExtensionAttribute {
  sint64 extension_attribute_type = 1 [(ASN1.asn1_type) = ASN1_INTEGER];
  bytes extension_attribute_value = 2 [(ASN1.asn1_type) = ASN1_OCTET_STRING];
}

message AuthorityKeyIdentifierExtension {
  bool critical = 1 [(ASN1.asn1_type) = ASN1_BOOLEAN];
  AuthorityKeyIdentifier extnValue = 2 [(ASN1.asn1_type) = ASN1_SEQUENCE];
}

message AuthorityKeyIdentifier {
  bytes keyIdentifier = 1 [(ASN1.asn1_type) = ASN1_OCTET_STRING];  // KeyIdentifier
  repeated GeneralName authorityCertIssuer = 2 [(ASN1.asn1_type) = ASN1_SEQUENCE];
  sint64 authoritySerialNumber = 3 [(ASN1.asn1_type) = ASN1_INTEGER];
}

message SubjectKeyIdentifier {
  bytes keyIdentifier = 1 [(ASN1.asn1_type) = ASN1_OCTET_STRING];  // KeyIdentifier
}

message KeyUsage {
  repeated KeyUsageBits keyUsage = 1;
}

enum KeyUsageBits {
  option allow_alias = true;
  KEYUSAGE_DIGITALSIGNATURE = 0;
  KEYUSAGE_NONREPUDIATION = 1;
  KEYUSAGE_CONTENTCOMMITMENT = 1;
  KEYUSAGE_KEYENCIPHERMENT = 2;
  KEYUSAGE_DATAENCIPHERMENT = 3;
  KEYUSAGE_KEYAGREEMENT = 4;
  KEYUSAGE_KEYCERTSIGN = 5;
  KEYUSAGE_CRLSIGN = 6;
  KEYUSAGE_ENCIPHERONLY = 7;
  KEYUSAGE_DECIPHERONLY = 8;
}

message CertificatePoliciesExtension {
  bool critical = 1 [(ASN1.asn1_type) = ASN1_BOOLEAN];
  CertificatePolicies extnValue = 2 [(ASN1.asn1_type) = ASN1_SEQUENCE];
}

message CertificatePolicies {
  repeated PolicyInformation policyInformation = 1 [(ASN1.asn1_type) = ASN1_SEQUENCE];
}

message PolicyInformation {
  string policyIdentifier = 1 [(ASN1.asn1_type) = ASN1_OBJECT_IDENTIFIER];
  repeated PolicyQualifierInfo policyQualifiers = 2 [(ASN1.asn1_type) = ASN1_SEQUENCE];
}

message PolicyQualifierInfo {
  string policyQualifierId = 1 [(ASN1.asn1_type) = ASN1_OBJECT_IDENTIFIER];  // id-qt-cps | id-qt-unotice
  oneof PolicyQualifierInfo_oneof {
    string cPSuri = 2 [(ASN1.asn1_type) = ASN1_IA5STRING];
    UserNotice userNotice = 3 [(ASN1.asn1_type) = ASN1_SEQUENCE];
  }
}

message UserNotice {
  NoticeReference noticeRef = 1 [(ASN1.asn1_type) = ASN1_SEQUENCE];
  DisplayText explicitText = 2 [(ASN1.asn1_type) = ASN1_SEQUENCE];
}

message NoticeReference {
  DisplayText organization = 1;
  repeated sint64 noticeNumbers = 2 [(ASN1.asn1_type) = ASN1_INTEGER];
}

message DisplayText {
  oneof DisplayText_oneof {
    string ia5String = 1 [(ASN1.asn1_type) = ASN1_IA5STRING];
    string visibleString = 2 [(ASN1.asn1_type) = ASN1_VISIBLESTRING];
    string bmpString = 3 [(ASN1.asn1_type) = ASN1_BMPSSTRING];
    string utf8String = 4 [(ASN1.asn1_type) = ASN1_UTF8STRING];
  }
}

message AuthorityInfoAccessExtension {
  bool critical = 1 [(ASN1.asn1_type) = ASN1_BOOLEAN];
  AuthorityInfoAccessSyntax extnValue = 2 [(ASN1.asn1_type) = ASN1_SEQUENCE];
}

message AuthorityInfoAccessSyntax {
  repeated AccessDescription sequence = 1 [(ASN1.asn1_type) = ASN1_SEQUENCE];
}

message AccessDescription {
  string accessMethod = 1 [(ASN1.asn1_type) = ASN1_OBJECT_IDENTIFIER];
  GeneralName accessLocation = 2 [(ASN1.asn1_type) = ASN1_SEQUENCE];
}

// CRLDistributionPoints = repeated DistributionPoint
message DistributionPoint {
  DistributionPointName distributionPoint = 1;
  ReasonFlags reasons = 2;
  repeated GeneralName cRLIssuer = 3 [(ASN1.asn1_type) = ASN1_SEQUENCE];
}

message DistributionPointName {
  repeated GeneralName fullName = 1 [(ASN1.asn1_type) = ASN1_SEQUENCE];
  RelativeDistinguishedName nameRelativeToCRLIssuer = 2;
}

message ReasonFlags {
  repeated ReasonFlagsBits reasonFlags = 1;
}

enum ReasonFlagsBits {
  REASONFLAGS_UNUSED = 0;
  REASONFLAGS_KEYCOMPROMISE = 1;
  REASONFLAGS_CACOMPROMISE = 2;
  REASONFLAGS_AFFILIATIONCHANGED = 3;
  REASONFLAGS_SUPERSEDED = 4;
  REASONFLAGS_CESSATIONOFOPERATION = 5;
  REASONFLAGS_CERTIFICATEHOLD = 6;
  REASONFLAGS_PRIVILEGEWITHDRAWN = 7;
  REASONFLAGS_AACOMPROMISE = 8;
}

