syntax = "proto3";

import "ASN1.proto";
import "Rfc5280.proto";

message AttributeCertificate {
  AttributeCertificateInfo acinfo = 1 [(ASN1.asn1_type) = ASN1_SEQUENCE];
  AlgorithmIdentifier signatureAlgorithm = 2 [(ASN1.asn1_type) = ASN1_SEQUENCE];
  bytes signatureValue = 3 [(ASN1.asn1_type) = ASN1_BIT_STRING];           // base64 encode the binary value
}

message AttributeCertificateInfo {
  AttCertVersion version = 1 [(ASN1.asn1_type) = ASN1_INTEGER];
  Holder holder = 2 [(ASN1.asn1_type) = ASN1_SEQUENCE];
  AttCertIssuer issuer = 3 [(ASN1.asn1_type) = ASN1_SEQUENCE];
  AlgorithmIdentifier signature = 4 [(ASN1.asn1_type) = ASN1_SEQUENCE];
  AttCertValidityPeriod attrCertValidityPeriod = 5 [(ASN1.asn1_type) = ASN1_SEQUENCE];
  repeated Attribute attributes = 6 [(ASN1.asn1_type) = ASN1_SEQUENCE];
  bytes issuerUniqueID = 7 [(ASN1.asn1_type) = ASN1_BIT_STRING];  // UniqueIdentifier
  repeated Extension extensions = 8 [(ASN1.asn1_type) = ASN1_SEQUENCE];
}

enum AttCertVersion {
  RFC5755_V1 = 0;
  RFC5755_V2 = 1;
}

message Holder {
  IssuerSerial baseCertificateID = 1 [(ASN1.asn1_type) = ASN1_SEQUENCE];
  repeated GeneralName entityName = 2 [(ASN1.asn1_type) = ASN1_SEQUENCE];
  ObjectDigestInfo objectDigestInfo = 3 [(ASN1.asn1_type) = ASN1_SEQUENCE];
}

message ObjectDigestInfo {
  DigestedObjectType digestedObjectType = 1 [(ASN1.asn1_type) = ASN1_ENUMERATED];
  string otherObjectTypeID = 2 [(ASN1.asn1_type) = ASN1_OBJECT_IDENTIFIER];
  AlgorithmIdentifier digestAlgorithm = 3 [(ASN1.asn1_type) = ASN1_SEQUENCE];
  bytes objectDigest = 4 [(ASN1.asn1_type) = ASN1_BIT_STRING];
}

enum DigestedObjectType {
  DIGESTEDOBJECTTYPE_PUBLICKEY = 0;
  DIGESTEDOBJECTTYPE_PUBLICKEYCERT = 1;
  DIGESTEDOBJECTTYPE_OTHEROBJECTTYPES = 2;
}

message AttCertIssuer {
  repeated GeneralName v1Form = 1 [(ASN1.asn1_type) = ASN1_SEQUENCE];
  V2Form v2Form = 2 [(ASN1.asn1_type) = ASN1_SEQUENCE];
}

message V2Form {
  repeated GeneralName issuerName = 1 [(ASN1.asn1_type) = ASN1_SEQUENCE];
  IssuerSerial baseCertificateID = 2 [(ASN1.asn1_type) = ASN1_SEQUENCE];
  ObjectDigestInfo objectDigestInfo = 3 [(ASN1.asn1_type) = ASN1_SEQUENCE];
}

message IssuerSerial {
  IssuerSerialDN issuer = 1 [(ASN1.asn1_type) = ASN1_SEQUENCE];
  sint64 serial = 2 [(ASN1.asn1_type) = ASN1_INTEGER];
  bytes issuerUID = 3 [(ASN1.asn1_type) = ASN1_BIT_STRING];  // UniqueIdentifier
}

message IssuerSerialDN {
  repeated GeneralName generalName = 1 [(ASN1.asn1_type) = ASN1_SEQUENCE];
  string rdnShorthand = 2 [(ASN1.asn1_type) = ASN1_SEQUENCE];
}

message AttCertValidityPeriod {
  string notBeforeTime = 1 [(ASN1.asn1_type) = ASN1_GENERALIZEDTIME]; // YYYYMMDDHHMMSSZ
  string notAfterTime = 2 [(ASN1.asn1_type) = ASN1_GENERALIZEDTIME]; // YYYYMMDDHHMMSSZ
}