name: .NET

on:
  push:

jobs:
  build:

    runs-on: ${{ matrix.os }}

    strategy:
        matrix:
            os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
    - uses: actions/checkout@v4
    - name: Create .NET global json file
      run: |
        echo '{"sdk": {"version": "8.0.416","rollForward": "latestFeature"}}' > global.json
    - name: Setup .NET
      uses: actions/setup-dotnet@v5
      with:
        global-json-file: global.json
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Proto files package
      run: |
        nuget pack PlatformCertificate.Proto.ProtoFiles.nuspec